# Generated by Django 4.0.3 on 2022-09-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_shoppingitem'),
        ('meal_plans', '0002_mealplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipe'),
        ),
    ]
